spring.application.name=AutomationEngine

server.servlet.context-path=/automation_engine
server.port=8085

logging.level.root=INFO
logging.file.name=/var/log/automationengine/app.log

logging.pattern.console=%d{HH:mm:ss.SSS} %-5p %C{1} --- %m%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5p %C{1} : %m%n

spring.datasource.url=jdbc:mysql://localhost:3306/exp_config
spring.datasource.username=root
spring.datasource.password=sikha@1473
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect